# development configuration
version: '3.9'
services:

  planets-service:
    build:
      context: .
      dockerfile: ./planets-service/Dockerfile
      target: 'develop-stage'
    command: /bin/bash -c "cargo watch -x run"
    volumes:
      - ./planets-service:/app
      - planets-service-cargo-cache:/usr/local/cargo/registry
      - planets-service-target-cache:/app/target

  satellites-service:
    build:
      context: .
      dockerfile: ./satellites-service/Dockerfile
      target: 'develop-stage'
    command: /bin/bash -c "cargo watch -x run"
    volumes:
      - ./satellites-service:/app
      - satellites-service-cargo-cache:/usr/local/cargo/registry
      - satellites-service-target-cache:/app/target

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
      target: 'develop-stage'
    command: /bin/bash -c "cargo watch -x run"
    volumes:
      - ./auth-service:/app
      - auth-service-cargo-cache:/usr/local/cargo/registry
      - auth-service-target-cache:/app/target

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile

volumes:
  planets-service-cargo-cache:
  planets-service-target-cache:
  satellites-service-cargo-cache:
  satellites-service-target-cache:
  auth-service-cargo-cache:
  auth-service-target-cache:
